function parsave_infewsabm_landmrkt(savefname,FarmerAtt,Tbaseprod,Tfarmpref,Tfarmprod,SOCNTWK,...
    CROPHIST,ANNINC,AVGPERACRE,DCSNST,EXPTPROD,WTAPRICE,FARMCOSTS,PROFIT,...
    REVENUE,PROD,Price,PRODACRES,sellrecord,buyrecord,exitfarm,LANDPRICE,...
    BBPSTATE,MAXREV,DEGREERANK)
% cd C:\Users\nrmagliocca\'OneDrive - The University of Alabama'\INFEWS\ABM_drive\Results\allbbp_hubs_landmrkt_allvar
% cd C:\Users\nrmagliocca\Box\INFEWS_Project\ABM_drive\Results\allbbp_hubs_landmrkt_allvar_osse_02182024
% cd C:\Users\nrmagliocca\Box\INFEWS_Project\ABM_drive\Results\onebbp_hubs_landmrkt_05242023
% cd C:\Users\nrmagliocca\Box\INFEWS_Project\ABM_drive\Results\allbbp_hubs_landmrkt_allvar_osse_gacalib_03112024
% cd C:\Users\nrmagliocca\Box\Socio-Agroclimatology\ABM_Drive\Results\allbbp_hub928_landmrkt_allvar_osse_ga_04152024
% cd(hubstr) 
save(savefname,'FarmerAtt','Tbaseprod','Tfarmpref','Tfarmprod','SOCNTWK','CROPHIST',...
    'ANNINC','AVGPERACRE','DCSNST','EXPTPROD','WTAPRICE','FARMCOSTS','PROFIT',...
    'REVENUE','PROD','Price','PRODACRES','sellrecord','buyrecord','exitfarm','LANDPRICE',...
    'BBPSTATE','MAXREV','DEGREERANK','-v7.3')
% cd C:\Users\nrmagliocca\Box\INFEWS_Project\ABM_drive\Code

end